version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: denao

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

